### PR TITLE
Convert project to a python package (library)  

### PR DESCRIPTION
**Pull request by gso-gso**
The current project is meant to be used as a python library by external applications (i.e. importing its modules). However, it is not correctly implemented in the form of a package and subpackages. This creates several problems when trying to import it from the outside. 

For example, `sys.path` must be used to tell python where the modules are located, and the import paths used in the project itself may conflict when sourced from outside the top directory. Other paths such as the location of resource files is also broken when trying to import the project from the outside (see customer case [00304836](https://community.silabs.com/5008Y00002EnarG)). In fact, the project itself must make use of `sys.path` for the exact same reasons, which is far from ideal.

The solution is to convert the project to a package that external applications can import directly. Ideally, the package should be available in the public PyPI repository for automatic installation as a dependency. This PR starts the process by adding the corresponding `__init__.py` files and restructuring the import paths.

### CODE REVIEW

**Comment by MarcDorval** [comment]
Thanks for this work.
Building Python packages is not something we're familiar with, so we definitely can use a little help making the project easier to import. We'll need some time to test it, and will merge if it works fine.

**Comment by gso-gso** [comment]
Sure no problem. I could assist you on this. We're using the project extensively for our product certification. If you decide to go serious and fully convert this to a public package, the next step would be to add a `pyproject.toml` and a pipeline that automatically builds and publishes the package on e.g. each release. An advantage of this approach is that the package automatically pulls all dependencies (such as paramiko, pyserial, etc), so you don't need to manually document their installation process in the `README`s.

**Comment by gso-gso** [comment]
@MarcDorval what is the status of this, do you see a chance to merge it?

**Comment by gso-gso** [comment]
@MarcDorval our team is starting a new project to create a GUI that makes use of this library. It would be very beneficial to push this forward. Consider that having this project as a library would make things as simple as `pip install wfx-common-tools`, and in any python file:

```python
import wfx-common-tools
```
What do you think? If you set green light I can quickly rebase this PR.

**Comment by MarcDorval** [comment]
I need to get my ideas clear on this, given that GitHub mentions conflicts in pds_compress.py and wfx_test_target.py.
If you can work out some changes on your side to avoid conflicts it would probably be faster (I haven't been using this in months).

**Comment by gso-gso** [comment]
Thanks for the reply. I just rebased the branch to include your latest changes. Now it should be mergeable.

To summarize the changes here:

1. Add `__init__.py` files to all folders in order to convert them to python modules
2. Change the import paths to relative paths. This is still necessary so that the library is agnostic to where it is being imported from. Once we publish this package in an official repository this can be reverted.
3. Replace "-" (hyphens) with "_" (underscores) in folders. Python doesn't admit hyphens in package/module names
4. Include the PDS compressed file in the library package and import it from there. This is to avoid having to hard-code the path of this file.

**Pull request merged**
